### PR TITLE
updated to ZenohUTranspoart, updated signature, fixed dependencies and added clang-format.sh

### LINKED ISSUE #23: rpc example using SocketUTransport fails with error
When starting rpc_client/rpc_server there is an error "[error] SocketUTransport::SocketUTransport():143,62002,test_rpc.app Socket connection Failed". Is there something to configure or is it a known error?

### PR DESCRIPTION
**Pull request by MaximilianToe**
This PR targets the following issues:
- Replaces SocketUTransport with ZenohUTransport
- update the signature of cleanupListener to make it compatible with the recent changes of up-cpp
- update the dependencies after the changes in up-cpp
- added clang-format.sh like in up-cpp

Closes #23 #24 #25 #27

### CODE REVIEW

File: lint/clang-format.sh [hunk 1]
```diff
@@ -0,0 +1,28 @@
+#!/bin/bash
```
Comment (PLeVasseur) [inline lint/clang-format.sh:1]: Please add Eclipse copyright notice matching other files, with 2025 as the copyright year.

Same for a few other files I see that are newly added.

File: pubsub/src/UTransportDomainSockets.h [hunk 2]
```diff
@@ -42,7 +42,7 @@ class UTransportDomainSockets : public transport::UTransport {
 
 	void notifyListener(const v1::UMessage& message);
 	void listenThread();  // listen for incoming messages (thread)
-	void cleanupListener(CallableConn listener) override {}
+	void cleanupListener(const CallableConn& listener) override {}
```
Comment (PLeVasseur) [inline pubsub/src/UTransportDomainSockets.h:45]: Is this file needed anymore, now that we're using the Zenoh transport? 🤔 I'm in favor of mercilessly cutting out code to make a more maintainable codebase.

File: rpc/src/main_rpc_client.cpp [hunk 3]
```diff
@@ -24,17 +24,18 @@
 #include <spdlog/spdlog.h>
```
Comment (PLeVasseur) [inline rpc/src/main_rpc_client.cpp:24]: I see a client and server for rpc. Am I missing where the source is for the publisher and subscriber in `pubsub`?

**Review by PLeVasseur — COMMENTED** [review]
Hey @MaximilianToe -- thanks for updating this! Left a few comments and questions.

File: pubsub/src/UTransportDomainSockets.h (hunk 2 above)
Comment (PLeVasseur) [reply pubsub/src/UTransportDomainSockets.h:45]: @MaximilianToe and I chatted.

Plan is:
1. merge this
2. he'll open another PR tackling `pubsub`
3. can then remove all traces of the socket transport from this repo

Lemme know if I got anything mixed Max!

**Review by PLeVasseur — APPROVED** [review]
Thanks for the quick turn-around and flexibility @MaximilianToe!

File: pubsub/src/UTransportDomainSockets.h (hunk 2 above)
Comment (MaximilianToe) [reply pubsub/src/UTransportDomainSockets.h:45]: Sounds good!
